Neos:
  RedirectHandler:
    NeosAdapter:
      # By default the redirect handling for removed nodes is activated.
      # If it is deactivated in your settings you will be able to handle the redirects on your own.
      # For example redirect to dedicated landing pages for deleted campaign NodeTypes
      enableRemovedNodeRedirect: true

      pathPrefixConfiguration: []
      #  '/sites/neosdemo/': false

      restrictByNodeType: []
      #  Neos.Neos:Document: true

      restrictByOldUriPrefix: []
      #  '/some/uri/path/': true

      # in some cases you might need to completely disable the automatic redirects
      # e.g. on cli, during imports or similar
      enableAutomaticRedirects: true
