<?php

declare(strict_types=1);

namespace PackageVersions;

use Composer\InstalledVersions;
use OutOfBoundsException;

class_exists(InstalledVersions::class);

/**
 * This class is generated by composer/package-versions-deprecated, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 *
 * @deprecated in favor of the Composer\InstalledVersions class provided by Composer 2. Require composer-runtime-api:^2 to ensure it is present.
 */
final class Versions
{
    /**
     * @deprecated please use {@see self::rootPackageName()} instead.
     *             This constant will be removed in version 2.0.0.
     */
    const ROOT_PACKAGE_NAME = 'neos/neos-base-distribution';

    /**
     * Array of all available composer packages.
     * Dont read this array from your calling code, but use the \PackageVersions\Versions::getVersion() method instead.
     *
     * @var array<string, string>
     * @internal
     */
    const VERSIONS          = array (
  'behat/transliterator' => 'v1.3.0@3c4ec1d77c3d05caa1f0bf8fb3aae4845005c7fc',
  'brick/math' => '0.9.2@dff976c2f3487d42c1db75a3b180e2b9f0e72ce0',
  'composer/ca-bundle' => '1.2.10@9fdb22c2e97a614657716178093cd1da90a64aa8',
  'composer/composer' => '2.1.3@fc5c4573aafce3a018eb7f1f8f91cea423970f2e',
  'composer/metadata-minifier' => '1.0.0@c549d23829536f0d0e984aaabbf02af91f443207',
  'composer/package-versions-deprecated' => '1.11.99.2@c6522afe5540d5fc46675043d3ed5a45a740b27c',
  'composer/semver' => '3.2.5@31f3ea725711245195f62e54ffa402d8ef2fdba9',
  'composer/spdx-licenses' => '1.5.5@de30328a7af8680efdc03e396aad24befd513200',
  'composer/xdebug-handler' => '2.0.1@964adcdd3a28bf9ed5d9ac6450064e0d71ed7496',
  'doctrine/annotations' => '1.13.1@e6e7b7d5b45a2f2abc5460cc6396480b2b1d321f',
  'doctrine/cache' => '1.11.3@3bb5588cec00a0268829cc4a518490df6741af9d',
  'doctrine/collections' => '1.6.7@55f8b799269a1a472457bd1a41b4f379d4cfba4a',
  'doctrine/common' => '2.13.3@f3812c026e557892c34ef37f6ab808a6b567da7f',
  'doctrine/dbal' => '2.13.2@8dd39d2ead4409ce652fd4f02621060f009ea5e4',
  'doctrine/deprecations' => 'v0.5.3@9504165960a1f83cc1480e2be1dd0a0478561314',
  'doctrine/event-manager' => '1.1.1@41370af6a30faa9dc0368c4a6814d596e81aba7f',
  'doctrine/inflector' => '1.4.4@4bd5c1cdfcd00e9e2d8c484f79150f67e5d355d9',
  'doctrine/instantiator' => '1.4.0@d56bf6102915de5702778fe20f2de3b2fe570b5b',
  'doctrine/lexer' => '1.2.1@e864bbf5904cb8f5bb334f99209b48018522f042',
  'doctrine/migrations' => '3.1.4@207210c57f6c15835e8d6228075cd235bd061efc',
  'doctrine/orm' => '2.7.5@01187c9260cd085529ddd1273665217cae659640',
  'doctrine/persistence' => '1.3.8@7a6eac9fb6f61bba91328f15aa7547f4806ca288',
  'doctrine/reflection' => '1.2.2@fa587178be682efe90d005e3a322590d6ebb59a5',
  'egulias/email-validator' => '3.1.1@c81f18a3efb941d8c4d2e025f6183b5c6d697307',
  'flowpack/neos-frontendlogin' => '4.2.0@3f75926802209e366680153bd104cde72399e26f',
  'friendsofphp/proxy-manager-lts' => 'v1.0.5@006aa5d32f887a4db4353b13b5b5095613e0611f',
  'gedmo/doctrine-extensions' => 'v3.1.0@0803fa56b13cf858951599027f451738078c49f8',
  'guzzlehttp/psr7' => '1.8.2@dc960a912984efb74d0a90222870c72c87f10c91',
  'imagine/imagine' => '1.2.4@d2e18be6e930ca169e4f921ef73ebfc061bf55d8',
  'justinrainbow/json-schema' => '5.2.10@2ba9c8c862ecd5510ed16c6340aa9f6eadb4f31b',
  'laminas/laminas-code' => '4.4.0@2b0bb59ade31a045fd3ff0097dc558bb896f6596',
  'league/csv' => '9.7.1@0ec57e8264ec92565974ead0d1724cf1026e10c1',
  'neos/cache' => '7.1.1@ada0231bda01c2db5b98d0984d85dda3e48d50e7',
  'neos/composer-plugin' => '2.1.2@0cd9a93955853733f04b6de037ced56d41d40f75',
  'neos/content-repository' => '7.1.0@43678ec5fdf963498fb0b776af247d1dfabb8bc4',
  'neos/demo' => '7.1.0@f2bef1f0de91d3075e76cc625322dc82468d3b75',
  'neos/diff' => '7.1.0@0d281908cb0b3a502f12d2e209a59cf70934f1fd',
  'neos/eel' => '7.1.1@e574391171f0db05caf2b78727e94e3f03c33fd6',
  'neos/error-messages' => '7.1.1@16f9d88ccbef64c49aa14a61d8cb4b7aab150959',
  'neos/flow' => '7.1.1@71a50a1bfd5b17e65ca78a562d9ce36b716a1cff',
  'neos/flow-log' => '7.1.1@bb7714795741ffa001a40d26854bb7ac47e1a90b',
  'neos/fluid-adaptor' => '7.1.1@c59fe95a94d03c37d8ca872aebaeca0387d4d5ce',
  'neos/form' => '5.2.1@25b2f051c2775aa52be349def82b9373ba5861a3',
  'neos/fusion' => '7.1.0@c5c05d4fa4939cbb97f56f60827e127f121e3ce0',
  'neos/fusion-afx' => '7.1.0@3774d2fd70769cc3448255d3dd52ff0b663fe811',
  'neos/fusion-form' => 'v2.0.2@e598e0400a114c5155bad4975cba83bba18be21b',
  'neos/http-factories' => '7.1.1@9e8c40ec772bd747bb3ce7ca7124e2b1abaf5558',
  'neos/imagine' => '3.2.0@2164a2d16c89c98aafde25317c06cd8015c6162e',
  'neos/kickstarter' => '7.1.1@f0dbff25b615db206fdf1276182ebf20082ca7e4',
  'neos/media' => '7.1.0@fbd3b5b179caba5259bf3b643076ac11a7b49d82',
  'neos/media-browser' => '7.1.0@60b66e8cf0cc36243008465755a491b5352e7c06',
  'neos/neos' => '7.1.0@55cc1be1f4cf347b09f83e4494282be0ac17cf39',
  'neos/neos-setup' => '1.1.3@9a4215fd80c438e95c4bb968f83c5e1493ca79c9',
  'neos/neos-ui' => '7.1.1@d3fea8c9b00f8e09f0ae805526e59e96e6e05ff7',
  'neos/neos-ui-compiled' => '7.1.1@6e0637f6f58d463046a4a42475191ed2fb24a1fc',
  'neos/nodetypes-assetlist' => '7.1.0@406b61e9d4abfbdc145e65aed920b54a033928f7',
  'neos/nodetypes-basemixins' => '7.1.0@94b424d989a962ff36f66b5373b16d0031e08a18',
  'neos/nodetypes-contentreferences' => '7.1.0@60fd186b88da15ce3b6c57000296b4312c287132',
  'neos/nodetypes-html' => '7.1.0@04a17ac51a0dc34199010450f4f4646895bed731',
  'neos/nodetypes-navigation' => '7.1.0@28dcc1df3fc85b547908238f336b06b0fb729f91',
  'neos/party' => '7.0.0@8eb0ba721c9d9c813f8e4e8653e1ba1eaaab0d4e',
  'neos/redirecthandler' => '5.0.0@e3f4dc9ba2f8dda101049feea23075d3c5182025',
  'neos/redirecthandler-databasestorage' => '5.0.0@2de39292bd6a1f59e1aec9e1a9f31ac6a7627151',
  'neos/redirecthandler-neosadapter' => '4.3.0@d04e1815f8105aa23c542f2ab2afdfb8d43fc01d',
  'neos/redirecthandler-ui' => '2.4.2@7bbbb7f026f7c6038225c762b0a60975d31d37cb',
  'neos/seo' => '3.2.0@9171b164beebe4eee25997976525d82381923a70',
  'neos/setup' => '5.0.0@2fd9b320ed455c0496a3b4f6db2b786baa9ffb4f',
  'neos/site-kickstarter' => '7.1.0@f0ff5c9e904debe033b26ead43361645209d557f',
  'neos/twitter-bootstrap' => '3.0.6@6defdd85a7f9beb24ed9137700c9fb64b1fb0925',
  'neos/utility-arrays' => '7.1.1@320b96ad3c960f9daeb093a5c87ee32a17a72a89',
  'neos/utility-files' => '7.1.1@bc7d56f8c8407f7a8058b7c2d11e4c215bcf401e',
  'neos/utility-mediatypes' => '7.1.1@ad857523c5c5497dc84890ef556859512a107ccc',
  'neos/utility-objecthandling' => '7.1.1@5dfac1f2dd09edd3ae360a404966888421adc1f1',
  'neos/utility-opcodecache' => '7.1.1@a886f98daddde3f8025a584b1b745350a9ade61f',
  'neos/utility-pdo' => '7.1.1@fdde28a92c6c54115e9b9f39318f72c7fab855c1',
  'neos/utility-schema' => '7.1.1@f83dc8f3a80b615cc93c4bd27561b93ef7c8df5e',
  'neos/utility-unicode' => '7.1.1@1725af3d455ebc8bee1e13ee32173ad7459a8489',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.1.1@8622567409010282b7aeebe4bb841fe98b58dcaf',
  'psr/http-factory' => '1.0.1@12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/http-server-handler' => '1.0.1@aff2f80e33b7f026ec96bb42f63242dc50ffcae7',
  'psr/http-server-middleware' => '1.0.1@2296f45510945530b9dceb8bcedb5cb84d40c5f5',
  'psr/log' => '1.1.4@d49695b909c3b7628b6289db5479a1c204601f11',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'ralouphie/getallheaders' => '3.0.3@120b605dfeb996808c31b6477290a714d356e822',
  'ramsey/collection' => '1.1.3@28a5c4ab2f5111db6a60b2b4ec84057e0f43b9c1',
  'ramsey/uuid' => '4.1.1@cd4032040a750077205918c86049aa0f43d22947',
  'react/promise' => 'v2.8.0@f3cff96a19736714524ca0dd1d4130de73dbbbc4',
  'seld/jsonlint' => '1.8.3@9ad6ce79c342fbd44df10ea95511a1b24dee5b57',
  'seld/phar-utils' => '1.1.1@8674b1d84ffb47cc59a101f5d5a3b61e87d23796',
  'symfony/console' => 'v5.3.2@649730483885ff2ca99ca0560ef0e5f6b03f2ac1',
  'symfony/deprecation-contracts' => 'v2.4.0@5f38c8804a9e97d23e0c8d63341088cd8a22d627',
  'symfony/dom-crawler' => 'v5.3.0@55fff62b19f413f897a752488ade1bc9c8a19cdd',
  'symfony/filesystem' => 'v5.3.0@348116319d7fb7d1faa781d26a48922428013eb2',
  'symfony/finder' => 'v5.3.0@0ae3f047bed4edff6fd35b26a9a6bfdc92c953c6',
  'symfony/polyfill-ctype' => 'v1.23.0@46cd95797e9df938fdd2b03693b5fca5e64b01ce',
  'symfony/polyfill-intl-grapheme' => 'v1.23.0@24b72c6baa32c746a4d0840147c9715e42bb68ab',
  'symfony/polyfill-intl-idn' => 'v1.23.0@65bd267525e82759e7d8c4e8ceea44f398838e65',
  'symfony/polyfill-intl-normalizer' => 'v1.23.0@8590a5f561694770bdcd3f9b5c69dde6945028e8',
  'symfony/polyfill-php80' => 'v1.23.0@eca0bf41ed421bed1b57c4958bab16aa86b757d0',
  'symfony/process' => 'v5.3.2@714b47f9196de61a196d86c4bad5f09201b307df',
  'symfony/service-contracts' => 'v2.4.0@f040a30e04b57fbcc9c6cbcf4dbaa96bd318b9bb',
  'symfony/stopwatch' => 'v5.3.0@313d02f59d6543311865007e5ff4ace05b35ee65',
  'symfony/string' => 'v5.3.2@0732e97e41c0a590f77e231afc16a327375d50b0',
  'symfony/yaml' => 'v5.3.2@71719ab2409401711d619765aa255f9d352a59b2',
  'typo3fluid/fluid' => '2.7.0@3420f8cfd6afcfa98e077f40b8d34f9be12f079e',
  'guzzlehttp/guzzle' => '7.3.0@7008573787b430c1c1f650e3722d9bba59967628',
  'guzzlehttp/promises' => '1.4.1@8e7d04f1f6450fef59366c399cfad4b9383aa30d',
  'mikey179/vfsstream' => 'v1.6.8@231c73783ebb7dd9ec77916c10037eff5a2b6efe',
  'myclabs/deep-copy' => '1.10.2@776f831124e9c62e1a2c601ecc52e776d8bb7220',
  'neos/behat' => '7.1.0@d2ad0790d19405b121ad1301770ddea579c318f4',
  'neos/buildessentials' => '7.1.0@6f88a259f9b51c92e44877c6fe5e3bd36d2d806f',
  'nikic/php-parser' => 'v4.10.5@4432ba399e47c66624bc73c8c0f811e5c109576f',
  'phar-io/manifest' => '2.0.1@85265efd3af7ba3ca4b2a2c34dbfc5788dd29133',
  'phar-io/version' => '3.1.0@bae7c545bef187884426f042434e561ab1ddb182',
  'phpdocumentor/reflection-common' => '2.2.0@1d01c49d4ed62f25aa84a747ad35d5a16924662b',
  'phpdocumentor/reflection-docblock' => '5.2.2@069a785b2141f5bcf49f3e353548dc1cce6df556',
  'phpdocumentor/type-resolver' => '1.4.0@6a467b8989322d92aa1c8bf2bebcc6e5c2ba55c0',
  'phpspec/prophecy' => '1.13.0@be1996ed8adc35c3fd795488a653f4b518be70ea',
  'phpunit/php-code-coverage' => '9.2.6@f6293e1b30a2354e8428e004689671b83871edde',
  'phpunit/php-file-iterator' => '3.0.5@aa4be8575f26070b100fccb67faabb28f21f66f8',
  'phpunit/php-invoker' => '3.1.1@5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
  'phpunit/php-text-template' => '2.0.4@5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
  'phpunit/php-timer' => '5.0.3@5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
  'phpunit/phpunit' => '9.5.6@fb9b8333f14e3dce976a60ef6a7e05c7c7ed8bfb',
  'psr/http-client' => '1.0.1@2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
  'sebastian/cli-parser' => '1.0.1@442e7c7e687e42adc03470c7b668bc4b2402c0b2',
  'sebastian/code-unit' => '1.0.8@1fc9f64c0927627ef78ba436c9b17d967e68e120',
  'sebastian/code-unit-reverse-lookup' => '2.0.3@ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
  'sebastian/comparator' => '4.0.6@55f4261989e546dc112258c7a75935a81a7ce382',
  'sebastian/complexity' => '2.0.2@739b35e53379900cc9ac327b2147867b8b6efd88',
  'sebastian/diff' => '4.0.4@3461e3fccc7cfdfc2720be910d3bd73c69be590d',
  'sebastian/environment' => '5.1.3@388b6ced16caa751030f6a69e588299fa09200ac',
  'sebastian/exporter' => '4.0.3@d89cc98761b8cb5a1a235a6b703ae50d34080e65',
  'sebastian/global-state' => '5.0.3@23bd5951f7ff26f12d4e3242864df3e08dec4e49',
  'sebastian/lines-of-code' => '1.0.3@c1c2e997aa3146983ed888ad08b15470a2e22ecc',
  'sebastian/object-enumerator' => '4.0.4@5c9eeac41b290a3712d88851518825ad78f45c71',
  'sebastian/object-reflector' => '2.0.4@b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
  'sebastian/recursion-context' => '4.0.4@cd9d8cf3c5804de4341c283ed787f099f5506172',
  'sebastian/resource-operations' => '3.0.3@0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8',
  'sebastian/type' => '2.3.4@b8cd8a1c753c90bc1a0f5372170e3e489136f914',
  'sebastian/version' => '3.0.2@c6c1022351a901512170118436c764e473f6de8c',
  'symfony/css-selector' => 'v2.8.52@7b1692e418d7ccac24c373528453bc90e42797de',
  'theseer/tokenizer' => '1.2.0@75a63c33a8577608444246075ea0af0d052e452a',
  'webmozart/assert' => '1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25',
  'neos/neos-base-distribution' => '7.1.0@',
);

    private function __construct()
    {
    }

    /**
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function rootPackageName() : string
    {
        if (!class_exists(InstalledVersions::class, false) || !(method_exists(InstalledVersions::class, 'getAllRawData') ? InstalledVersions::getAllRawData() : InstalledVersions::getRawData())) {
            return self::ROOT_PACKAGE_NAME;
        }

        return InstalledVersions::getRootPackage()['name'];
    }

    /**
     * @throws OutOfBoundsException If a version cannot be located.
     *
     * @psalm-param key-of<self::VERSIONS> $packageName
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function getVersion(string $packageName): string
    {
        if (class_exists(InstalledVersions::class, false) && (method_exists(InstalledVersions::class, 'getAllRawData') ? InstalledVersions::getAllRawData() : InstalledVersions::getRawData())) {
            return InstalledVersions::getPrettyVersion($packageName)
                . '@' . InstalledVersions::getReference($packageName);
        }

        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files'
        );
    }
}
