Neos:
  RedirectHandler:
    features:
      hitCounter: false
    statusCode:
      redirect: 301
      gone: 410
    validation:
      sourceUriPath: '/^[a-z0-9_\-\/\.]+$/i'
  Flow:
    http:
      middlewares:
        redirect:
          position: 'after routing'
          middleware: 'Neos\RedirectHandler\RedirectMiddleware'
